### ISSUE TITLE
@ada/api throws error when ttypescript

### ISSUE THREAD

**Issue by joseaparicioquake** [aws-solutions/automated-data-analytics-on-aws#69]
**Describe the bug**
I want to customize the way the solution creates connections to the RDS with glue, using connectors with our transit gateway, trying to setup this solution using the github repo and following the README file steps, rather than CFT template way.
I am using EC2 linux machine with Ubuntu as recommended per documentation for this setup.

However, when running ./run-all-tests.sh  on building the api, it throws this error.

```
@ada/athena-utilities: [INFO] BUILD SUCCESS
@ada/athena-utilities: [INFO] ------------------------------------------------------------------------
@ada/athena-utilities: [INFO] Total time:  29.391 s
@ada/athena-utilities: [INFO] Finished at: 2024-02-28T14:58:53Z
@ada/athena-utilities: [INFO] ------------------------------------------------------------------------
@ada/cdk-core: $ yarn run compile
@ada/cdk-core: $ tsc
@ada/api: $ yarn clean && yarn generate
@ada/api: $ rm -rf build client docs
@ada/api: $ yarn generate:openapi
@ada/api: $ ts-node -C ttypescript ./generators/openapi/generate.ts
@ada/api: /home/ubuntu/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:13
@ada/api:         function __() { this.constructor = d; }
@ada/api:                                          ^
@ada/api: TypeError: Cannot set property constructor of [object Object] which has only a getter
@ada/api:     at new __ (/home/ubuntu/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:13:42)
@ada/api:     at __extends (/home/ubuntu/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:14:84)
@ada/api:     at /home/ubuntu/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:65:5
@ada/api:     at Object.<anonymous> (/home/ubuntu/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:100:2)
@ada/api:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
@ada/api:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
@ada/api:     at Module.load (node:internal/modules/cjs/loader:1076:32)
@ada/api:     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
@ada/api:     at Module.require (node:internal/modules/cjs/loader:1100:19)
@ada/api:     at require (node:internal/modules/cjs/helpers:119:18)
@ada/api: error Command failed with exit code 1.
@ada/api: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@ada/api: error Command failed with exit code 1.
@ada/api: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@ada/api: error Command failed with exit code 1.
@ada/api: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@ada/api'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
Follow all the steps given in README.md file at the root of the project
Use an EC2 with Ubuntu as SO, on an public subnet with IGW
run the script file "./run-all-tests.sh"

**Expected behavior**
Build should complete successfully

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.3.0]

- [x] Region: [us-east-1]
- [] Was the solution modified from the version published on this repository?
- [] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?[Yes]
- [x] Were there any errors in the CloudWatch Logs?[No]

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![image](https://github.com/aws-solutions/automated-data-analytics-on-aws/assets/148251545/cb93f31b-7aef-41ee-a1d8-31b253bbecc9)

**Additional context**

**Comment by dougtoppin** [comment]
@joseaparicioquake thanks for your report, I duplicated this as well, we will investigate and get back to you

**Comment by dougtoppin** [comment]
@joseaparicioquake This issue should now be resolved in the v1.4.0 release
